title: Nekladek
description: Trying to make this thing work
theme: just-the-docs

url: https://nekladek.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
